//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 09.07.2014 23:08:20
namespace WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel
{
    /// <summary>
    /// There are no comments for AnimalTypeSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("AnimalTypeSingle")]
    public partial class AnimalTypeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<AnimalType>
    {
        /// <summary>
        /// Initialize a new AnimalTypeSingle object.
        /// </summary>
        public AnimalTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AnimalTypeSingle object.
        /// </summary>
        public AnimalTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for EventData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventData> EventData
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._EventData == null))
                {
                    this._EventData = Context.CreateQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventData>(GetPath("EventData"));
                }
                return this._EventData;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventData> _EventData;
    }
    /// <summary>
    /// There are no comments for AnimalType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Key
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Key")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("AnimalType")]
    public partial class AnimalType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new AnimalType object.
        /// </summary>
        /// <param name="key">Initial value of Key.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static AnimalType CreateAnimalType(long key)
        {
            AnimalType animalType = new AnimalType();
            animalType.Key = key;
            return animalType;
        }
        /// <summary>
        /// There are no comments for Property Key in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Key")]
        public long Key
        {
            get
            {
                return this._Key;
            }
            set
            {
                this.OnKeyChanging(value);
                this._Key = value;
                this.OnKeyChanged();
                this.OnPropertyChanged("Key");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private long _Key;
        partial void OnKeyChanging(long value);
        partial void OnKeyChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property MeanCost in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MeanCost")]
        public global::System.Nullable<double> MeanCost
        {
            get
            {
                return this._MeanCost;
            }
            set
            {
                this.OnMeanCostChanging(value);
                this._MeanCost = value;
                this.OnMeanCostChanged();
                this.OnPropertyChanged("MeanCost");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::System.Nullable<double> _MeanCost;
        partial void OnMeanCostChanging(global::System.Nullable<double> value);
        partial void OnMeanCostChanged();
        /// <summary>
        /// There are no comments for Property EventData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EventData")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventData> EventData
        {
            get
            {
                return this._EventData;
            }
            set
            {
                this.OnEventDataChanging(value);
                this._EventData = value;
                this.OnEventDataChanged();
                this.OnPropertyChanged("EventData");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventData> _EventData = new global::Microsoft.OData.Client.DataServiceCollection<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventData>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnEventDataChanging(global::Microsoft.OData.Client.DataServiceCollection<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventData> value);
        partial void OnEventDataChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for EventDataSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("EventDataSingle")]
    public partial class EventDataSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<EventData>
    {
        /// <summary>
        /// Initialize a new EventDataSingle object.
        /// </summary>
        public EventDataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new EventDataSingle object.
        /// </summary>
        public EventDataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for AnimalType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalTypeSingle AnimalType
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._AnimalType == null))
                {
                    this._AnimalType = new global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalTypeSingle(this.Context, GetPath("AnimalType"));
                }
                return this._AnimalType;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalTypeSingle _AnimalType;
    }
    /// <summary>
    /// There are no comments for EventData in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EventDataId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("EventDataId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("EventData")]
    public partial class EventData : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new EventData object.
        /// </summary>
        /// <param name="eventDataId">Initial value of EventDataId.</param>
        /// <param name="factor">Initial value of Factor.</param>
        /// <param name="fixChange">Initial value of FixChange.</param>
        /// <param name="animalTypeId">Initial value of AnimalTypeId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static EventData CreateEventData(long eventDataId, int factor, double fixChange, long animalTypeId)
        {
            EventData eventData = new EventData();
            eventData.EventDataId = eventDataId;
            eventData.Factor = factor;
            eventData.FixChange = fixChange;
            eventData.AnimalTypeId = animalTypeId;
            return eventData;
        }
        /// <summary>
        /// There are no comments for Property EventDataId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EventDataId")]
        public long EventDataId
        {
            get
            {
                return this._EventDataId;
            }
            set
            {
                this.OnEventDataIdChanging(value);
                this._EventDataId = value;
                this.OnEventDataIdChanged();
                this.OnPropertyChanged("EventDataId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private long _EventDataId;
        partial void OnEventDataIdChanging(long value);
        partial void OnEventDataIdChanged();
        /// <summary>
        /// There are no comments for Property Factor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Factor")]
        public int Factor
        {
            get
            {
                return this._Factor;
            }
            set
            {
                this.OnFactorChanging(value);
                this._Factor = value;
                this.OnFactorChanged();
                this.OnPropertyChanged("Factor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _Factor;
        partial void OnFactorChanging(int value);
        partial void OnFactorChanged();
        /// <summary>
        /// There are no comments for Property StringTestId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("StringTestId")]
        public string StringTestId
        {
            get
            {
                return this._StringTestId;
            }
            set
            {
                this.OnStringTestIdChanging(value);
                this._StringTestId = value;
                this.OnStringTestIdChanged();
                this.OnPropertyChanged("StringTestId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _StringTestId;
        partial void OnStringTestIdChanging(string value);
        partial void OnStringTestIdChanged();
        /// <summary>
        /// There are no comments for Property FixChange in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FixChange")]
        public double FixChange
        {
            get
            {
                return this._FixChange;
            }
            set
            {
                this.OnFixChangeChanging(value);
                this._FixChange = value;
                this.OnFixChangeChanged();
                this.OnPropertyChanged("FixChange");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private double _FixChange;
        partial void OnFixChangeChanging(double value);
        partial void OnFixChangeChanged();
        /// <summary>
        /// There are no comments for Property AnimalTypeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AnimalTypeId")]
        public long AnimalTypeId
        {
            get
            {
                return this._AnimalTypeId;
            }
            set
            {
                this.OnAnimalTypeIdChanging(value);
                this._AnimalTypeId = value;
                this.OnAnimalTypeIdChanged();
                this.OnPropertyChanged("AnimalTypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private long _AnimalTypeId;
        partial void OnAnimalTypeIdChanging(long value);
        partial void OnAnimalTypeIdChanged();
        /// <summary>
        /// There are no comments for Property AnimalType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AnimalType")]
        public global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalType AnimalType
        {
            get
            {
                return this._AnimalType;
            }
            set
            {
                this.OnAnimalTypeChanging(value);
                this._AnimalType = value;
                this.OnAnimalTypeChanged();
                this.OnPropertyChanged("AnimalType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalType _AnimalType;
        partial void OnAnimalTypeChanging(global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalType value);
        partial void OnAnimalTypeChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PlayerSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PlayerSingle")]
    public partial class PlayerSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Player>
    {
        /// <summary>
        /// Initialize a new PlayerSingle object.
        /// </summary>
        public PlayerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PlayerSingle object.
        /// </summary>
        public PlayerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for PlayerStats in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStatsSingle PlayerStats
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PlayerStats == null))
                {
                    this._PlayerStats = new global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStatsSingle(this.Context, GetPath("PlayerStats"));
                }
                return this._PlayerStats;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStatsSingle _PlayerStats;
    }
    /// <summary>
    /// There are no comments for Player in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Player")]
    public partial class Player : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Player object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static Player CreatePlayer(long ID)
        {
            Player player = new Player();
            player.Id = ID;
            return player;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Email")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property PlayerStats in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PlayerStats")]
        public global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStats PlayerStats
        {
            get
            {
                return this._PlayerStats;
            }
            set
            {
                this.OnPlayerStatsChanging(value);
                this._PlayerStats = value;
                this.OnPlayerStatsChanged();
                this.OnPropertyChanged("PlayerStats");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStats _PlayerStats;
        partial void OnPlayerStatsChanging(global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStats value);
        partial void OnPlayerStatsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PlayerStatsSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PlayerStatsSingle")]
    public partial class PlayerStatsSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PlayerStats>
    {
        /// <summary>
        /// Initialize a new PlayerStatsSingle object.
        /// </summary>
        public PlayerStatsSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PlayerStatsSingle object.
        /// </summary>
        public PlayerStatsSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for Player in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerSingle Player
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Player == null))
                {
                    this._Player = new global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerSingle(this.Context, GetPath("Player"));
                }
                return this._Player;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerSingle _Player;
    }
    /// <summary>
    /// There are no comments for PlayerStats in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PlayerId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PlayerId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("PlayerStats")]
    public partial class PlayerStats : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PlayerStats object.
        /// </summary>
        /// <param name="playerStatsId">Initial value of PlayerStatsId.</param>
        /// <param name="skillLevel">Initial value of SkillLevel.</param>
        /// <param name="playerId">Initial value of PlayerId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static PlayerStats CreatePlayerStats(long playerStatsId, int skillLevel, long playerId)
        {
            PlayerStats playerStats = new PlayerStats();
            playerStats.PlayerStatsId = playerStatsId;
            playerStats.SkillLevel = skillLevel;
            playerStats.PlayerId = playerId;
            return playerStats;
        }
        /// <summary>
        /// There are no comments for Property PlayerStatsId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PlayerStatsId")]
        public long PlayerStatsId
        {
            get
            {
                return this._PlayerStatsId;
            }
            set
            {
                this.OnPlayerStatsIdChanging(value);
                this._PlayerStatsId = value;
                this.OnPlayerStatsIdChanged();
                this.OnPropertyChanged("PlayerStatsId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private long _PlayerStatsId;
        partial void OnPlayerStatsIdChanging(long value);
        partial void OnPlayerStatsIdChanged();
        /// <summary>
        /// There are no comments for Property SkillLevel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SkillLevel")]
        public int SkillLevel
        {
            get
            {
                return this._SkillLevel;
            }
            set
            {
                this.OnSkillLevelChanging(value);
                this._SkillLevel = value;
                this.OnSkillLevelChanged();
                this.OnPropertyChanged("SkillLevel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _SkillLevel;
        partial void OnSkillLevelChanging(int value);
        partial void OnSkillLevelChanged();
        /// <summary>
        /// There are no comments for Property HighScore in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HighScore")]
        public string HighScore
        {
            get
            {
                return this._HighScore;
            }
            set
            {
                this.OnHighScoreChanging(value);
                this._HighScore = value;
                this.OnHighScoreChanged();
                this.OnPropertyChanged("HighScore");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _HighScore;
        partial void OnHighScoreChanging(string value);
        partial void OnHighScoreChanged();
        /// <summary>
        /// There are no comments for Property PlayerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PlayerId")]
        public long PlayerId
        {
            get
            {
                return this._PlayerId;
            }
            set
            {
                this.OnPlayerIdChanging(value);
                this._PlayerId = value;
                this.OnPlayerIdChanged();
                this.OnPropertyChanged("PlayerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private long _PlayerId;
        partial void OnPlayerIdChanging(long value);
        partial void OnPlayerIdChanged();
        /// <summary>
        /// There are no comments for Property Player in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Player")]
        public global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.Player Player
        {
            get
            {
                return this._Player;
            }
            set
            {
                this.OnPlayerChanging(value);
                this._Player = value;
                this.OnPlayerChanged();
                this.OnPropertyChanged("Player");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.Player _Player;
        partial void OnPlayerChanging(global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.Player value);
        partial void OnPlayerChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SkillLevelsSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SkillLevelsSingle")]
    public partial class SkillLevelsSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<SkillLevels>
    {
        /// <summary>
        /// Initialize a new SkillLevelsSingle object.
        /// </summary>
        public SkillLevelsSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new SkillLevelsSingle object.
        /// </summary>
        public SkillLevelsSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for Levels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevel> Levels
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Levels == null))
                {
                    this._Levels = Context.CreateQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevel>(GetPath("Levels"));
                }
                return this._Levels;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevel> _Levels;
    }
    /// <summary>
    /// There are no comments for SkillLevels in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("SkillLevels")]
    public partial class SkillLevels : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SkillLevels object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static SkillLevels CreateSkillLevels(int ID)
        {
            SkillLevels skillLevels = new SkillLevels();
            skillLevels.Id = ID;
            return skillLevels;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Levels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Levels")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevel> Levels
        {
            get
            {
                return this._Levels;
            }
            set
            {
                this.OnLevelsChanging(value);
                this._Levels = value;
                this.OnLevelsChanged();
                this.OnPropertyChanged("Levels");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevel> _Levels = new global::Microsoft.OData.Client.DataServiceCollection<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevel>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnLevelsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevel> value);
        partial void OnLevelsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SkillLevelSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SkillLevelSingle")]
    public partial class SkillLevelSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<SkillLevel>
    {
        /// <summary>
        /// Initialize a new SkillLevelSingle object.
        /// </summary>
        public SkillLevelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new SkillLevelSingle object.
        /// </summary>
        public SkillLevelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}
        /// <summary>
        /// There are no comments for PlayerStats in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStatsSingle PlayerStats
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PlayerStats == null))
                {
                    this._PlayerStats = new global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStatsSingle(this.Context, GetPath("PlayerStats"));
                }
                return this._PlayerStats;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStatsSingle _PlayerStats;
    }
    /// <summary>
    /// There are no comments for SkillLevel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Level
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Level")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("SkillLevel")]
    public partial class SkillLevel : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SkillLevel object.
        /// </summary>
        /// <param name="level">Initial value of Level.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public static SkillLevel CreateSkillLevel(int level)
        {
            SkillLevel skillLevel = new SkillLevel();
            skillLevel.Level = level;
            return skillLevel;
        }
        /// <summary>
        /// There are no comments for Property Level in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Level")]
        public int Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                this.OnLevelChanging(value);
                this._Level = value;
                this.OnLevelChanged();
                this.OnPropertyChanged("Level");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private int _Level;
        partial void OnLevelChanging(int value);
        partial void OnLevelChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property PlayerStats in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PlayerStats")]
        public global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStats PlayerStats
        {
            get
            {
                return this._PlayerStats;
            }
            set
            {
                this.OnPlayerStatsChanging(value);
                this._PlayerStats = value;
                this.OnPlayerStatsChanged();
                this.OnPropertyChanged("PlayerStats");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStats _PlayerStats;
        partial void OnPlayerStatsChanging(global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStats value);
        partial void OnPlayerStatsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalType as global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalType> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalTypeSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventData as global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventDataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventDataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventData> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventDataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.Player as global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.Player> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStats as global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStatsSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStatsSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStats> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.PlayerStatsSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevels as global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevelsSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevelsSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevels> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevelsSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevel as global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevelSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevel> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevelSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace WebAPIODataV4.Client.Default
{
    /// <summary>
    /// There are no comments for SqliteContext in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SqliteContext")]
    public partial class SqliteContext : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new SqliteContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public SqliteContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "WebAPIODataV4SQLite.DomainModel", "WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "WebAPIODataV4.Client.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("WebAPIODataV4SQLite.DomainModel.", originalNameAttribute.OriginalName);
                }
                return string.Concat("WebAPIODataV4SQLite.DomainModel.", clientType.Name);
            }
            if (clientType.Namespace.Equals("WebAPIODataV4.Client.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for AnimalType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalType> AnimalType
        {
            get
            {
                if ((this._AnimalType == null))
                {
                    this._AnimalType = base.CreateQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalType>("AnimalType");
                }
                return this._AnimalType;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalType> _AnimalType;
        /// <summary>
        /// There are no comments for EventData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventData> EventData
        {
            get
            {
                if ((this._EventData == null))
                {
                    this._EventData = base.CreateQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventData>("EventData");
                }
                return this._EventData;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventData> _EventData;
        /// <summary>
        /// There are no comments for Player in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.Player> Player
        {
            get
            {
                if ((this._Player == null))
                {
                    this._Player = base.CreateQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.Player>("Player");
                }
                return this._Player;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.Player> _Player;
        /// <summary>
        /// There are no comments for AnimalType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public void AddToAnimalType(global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.AnimalType animalType)
        {
            base.AddObject("AnimalType", animalType);
        }
        /// <summary>
        /// There are no comments for EventData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public void AddToEventData(global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.EventData eventData)
        {
            base.AddObject("EventData", eventData);
        }
        /// <summary>
        /// There are no comments for Player in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public void AddToPlayer(global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.Player player)
        {
            base.AddObject("Player", player);
        }
        /// <summary>
        /// There are no comments for SkillLevels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        public global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevelsSingle SkillLevels
        {
            get
            {
                if ((this._SkillLevels == null))
                {
                    this._SkillLevels = new global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevelsSingle(this, "SkillLevels");
                }
                return this._SkillLevels;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private global::WebAPIODataV4.Client.WebAPIODataV4SQLite.DomainModel.SkillLevelsSingle _SkillLevels;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""WebAPIODataV4SQLite.DomainModel"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""AnimalType"">
        <Key>
          <PropertyRef Name=""Key"" />
        </Key>
        <Property Name=""Key"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""MeanCost"" Type=""Edm.Double"" />
        <NavigationProperty Name=""EventData"" Type=""Collection(WebAPIODataV4SQLite.DomainModel.EventData)"" />
      </EntityType>
      <EntityType Name=""EventData"">
        <Key>
          <PropertyRef Name=""EventDataId"" />
        </Key>
        <Property Name=""EventDataId"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""Factor"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""StringTestId"" Type=""Edm.String"" />
        <Property Name=""FixChange"" Type=""Edm.Double"" Nullable=""false"" />
        <Property Name=""AnimalTypeId"" Type=""Edm.Int64"" Nullable=""false"" />
        <NavigationProperty Name=""AnimalType"" Type=""WebAPIODataV4SQLite.DomainModel.AnimalType"" />
      </EntityType>
      <EntityType Name=""Player"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Email"" Type=""Edm.String"" />
        <NavigationProperty Name=""PlayerStats"" Type=""WebAPIODataV4SQLite.DomainModel.PlayerStats"" ContainsTarget=""true"" />
      </EntityType>
      <EntityType Name=""PlayerStats"">
        <Key>
          <PropertyRef Name=""PlayerId"" />
        </Key>
        <Property Name=""PlayerStatsId"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""SkillLevel"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""HighScore"" Type=""Edm.String"" />
        <Property Name=""PlayerId"" Type=""Edm.Int64"" Nullable=""false"" />
        <NavigationProperty Name=""Player"" Type=""WebAPIODataV4SQLite.DomainModel.Player"" />
      </EntityType>
      <EntityType Name=""SkillLevels"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""Levels"" Type=""Collection(WebAPIODataV4SQLite.DomainModel.SkillLevel)"" ContainsTarget=""true"" />
      </EntityType>
      <EntityType Name=""SkillLevel"">
        <Key>
          <PropertyRef Name=""Level"" />
        </Key>
        <Property Name=""Level"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Description"" Type=""Edm.String"" />
        <NavigationProperty Name=""PlayerStats"" Type=""WebAPIODataV4SQLite.DomainModel.PlayerStats"" ContainsTarget=""true"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""SqliteContext"">
        <EntitySet Name=""AnimalType"" EntityType=""WebAPIODataV4SQLite.DomainModel.AnimalType"">
          <NavigationPropertyBinding Path=""EventData"" Target=""EventData"" />
        </EntitySet>
        <EntitySet Name=""EventData"" EntityType=""WebAPIODataV4SQLite.DomainModel.EventData"">
          <NavigationPropertyBinding Path=""AnimalType"" Target=""AnimalType"" />
        </EntitySet>
        <EntitySet Name=""Player"" EntityType=""WebAPIODataV4SQLite.DomainModel.Player"" />
        <Singleton Name=""SkillLevels"" Type=""WebAPIODataV4SQLite.DomainModel.SkillLevels"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
    }
}
